baseURL       = "https://gracious-hermann-c61485.netlify.app"
languageCode  = "en-us"
title         = "Charles SAUVAT - Développeur web & mobile / Rouen"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = ""
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = ""
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = ""
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = ""
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = ""
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "En savoir plus sur moi"
    url     = "about"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = ""
    heading               = ""
    tagline               = ""
    primary_button        = ""
    primary_button_url    = ""
    secondary_button      = ""
    secondary_button_url  = ""

  [params.portfolio]
    enable    = true
    title     = "OUR RECENT WORKS"
    subtitle  = "Crafting experiences and seeking to make the complex clear & beautiful."

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "713 Elmwood St.<br>Prior Lake, MN 55372"
      phone   = "409-896-1444"
      email   = "info@roxo.co"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Menu de navigation"
        [[params.footer.sitemap.link]]
          name = "A propos"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Projets"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Réseaux sociaux"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://instagram.com/"
        [[params.footer.social.link]]
          name = "Linkedin"
          url  = "#"
        [[params.footer.social.link]]
          name = "Facebook"
          url  = "#"
        [[params.footer.social.link]]
          name = "Twitter"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "Vous voulez en savoir plus"
        description = "Si vous voulez en savoir plus vous pouvez m'envoyer un mail à charles@sauvat.pro"
